from nipyapi import canvas, nifi
from .create_processor_updateattribute import CreateProcessorUpdateAttribute
import json

class CreateProcessorAvroSchema(CreateProcessorUpdateAttribute):

    type = None

    def __init__(self, process_group, processor_name, location, processor_config):
        CreateProcessorUpdateAttribute.__init__(self, process_group, processor_name, location, processor_config)

        fields = []
        for field in processor_config.get("properties").get("avroschema.schema", ""):
            fields.append({ "name" : field[0], "type" : [ "null", field[1] ] })
        
        self.config.properties.update(
            {"avro.schema":
            '{"type" : "record", "name" : "avro_schema", "doc" : "Schema generated by Kite", "fields" :' + str(json.dumps(fields)) + '}'})
        self.config.properties.update({"datepartition": processor_config.get("properties").get("avroschema.datepartition", "")})
        self.config.properties.update({"hourpartition": processor_config.get("properties").get("avroschema.hourpartition", "")})

    def create(self):        
        return CreateProcessorUpdateAttribute.create(self)