from vvdatalab_nifi_flow_generator.models.nifi_component import NifiComponent
from vvdatalab_nifi_flow_generator.models.create_location import CreateLocation
from vvdatalab_nifi_flow_generator.models.create_location import LocationType
from vvdatalab_nifi_flow_generator.models.link_component import LinkComponent

from .process_groups.create_process_group import CreateProcessGroup

from .processors.creations.create_processor import CreateProcessor
from .processors.creations.create_processor_getsftp import CreateProcessorGetSFTP
from .processors.creations.create_processor_routetext import CreateProcessorRouteText
from .processors.creations.update_attribute.create_processor_updateattribute import CreateProcessorUpdateAttribute
from .processors.creations.update_attribute.create_processor_avroschema import CreateProcessorAvroSchema
from .processors.creations.create_processor_convertrecord import CreateProcessorConvertRecord
from .processors.creations.create_processor_convertavrotoorc import CreateProcessorConvertAvroToOrc
from .processors.creations.create_processor_puthdfs import CreateProcessorPutHDFS
from .processors.creations.replace_text.create_processor_replacetext import CreateProcessorReplaceText
from .processors.creations.replace_text.create_processor_queryinsertvalues import CreateProcessorQueryInsertValues
from .processors.creations.replace_text.create_processor_constructquery import CreateProcessorConstructQuery
from .processors.creations.create_processor_puthiveql import CreateProcessorPutHiveQl
from .processors.creations.create_processor_queryrecord import CreateProcessorQueryRecord
from .processors.creations.create_processor_splitjson import CreateProcessorSplitJson
from .processors.creations.create_processor_evaluatejsonpath import CreateProcessorEvaluateJsonPath
from .processors.creations.create_processor_mergecontent import CreateProcessorMergeContent
from .processors.creations.create_processor_fetchhdfs import CreateProcessorFetchHDFS
from .processors.creations.create_processor_convertcharacterset import CreateProcessorConvertCharacterSet
from .processors.creations.create_processor_splittext import CreateProcessorSplitText
from .processors.creations.create_processor_consumekafka import CreateProcessorConsumeKafka
from .processors.creations.create_processor_routeonattribute import CreateProcessorRouteOnAttribute
from .processors.creations.create_processor_attributestojson import CreateProcessorAttributesToJson
from .processors.creations.create_processor_publishkafka import CreateProcessorPublishKafka

from .processors.connections.create_connection import CreateConnection
from .processors.connections.connection_to_input_port import ConnectionToInputPort
from .processors.connections.connection_from_output_port import ConnectionFromOutputPort

from .io_ports.create_io_group import CreateIOGroup